### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by jtrautmann** [domschrei/aquaplanning#22] opened 2019-01-28 11:15 UTC
I ran the `TestPlanners` test cases as it is without changing anything and the `testDerivedPredicates()` method returned an error message:

> Testing domain "testfiles/derivedPredicates/domain1.pddl", problem "testfiles/derivedPredicates/p1.pddl".
> Parsing ...
> Grounding ...
> Planning ...
> 0 : (turn4 o4)
> 1 : (turn4 o3)
> 
> [0,286] Error at step 1: Action (turn4 o4) PRE: { { AND (is-any) ¬(eq-o1-or-o2-or-o3 o4) } } POST: {  {3} }} is not applicable in state { (_TRUE) }.

In the `TestParallelPlanning` test as it is without changing anything, the `testParallelPlanner()` method also returned invalid plans. This might be the same error as the above one. There were error for the rover domain like this one:

> Testing planner on /home/jeremias/Programmieren/KIT/APS/aquaplanning/benchmarks/Rover/p03.pddl
> [65,457] Error at step 7: Action (calibrate rover0 camera0 objective0 waypoint1) PRE: {  {4, 25, 26, 27, 28} } POST: {  {29} }} is not applicable in state { (available rover0) (can_traverse rover0 waypoint1 waypoint2) (visible waypoint1 waypoint2) (at rover0 waypoint2) (can_traverse rover0 waypoint1 waypoint5) (visible waypoint1 waypoint5) (available rover1) (at rover1 waypoint2) (can_traverse rover1 waypoint2 waypoint0) (can_traverse rover1 waypoint2 waypoint3) (visible waypoint2 waypoint3) (at rover1 waypoint3) (can_traverse rover1 waypoint2 waypoint5) (visible waypoint2 waypoint5) (equipped_for_imaging rover0) (calibration_target camera0 objective0) (visible_from objective0 waypoint1) (on_board camera0 rover0) (calibration_target camera1 objective0) (on_board camera1 rover0) (can_traverse rover0 waypoint2 waypoint0) (can_traverse rover0 waypoint2 waypoint1) (visible waypoint2 waypoint1) (can_traverse rover0 waypoint5 waypoint1) (visible waypoint5 waypoint1) (can_traverse rover1 waypoint0 waypoint2) (visible waypoint0 waypoint2) (can_traverse rover1 waypoint3 waypoint1) (visible waypoint3 waypoint1) (can_traverse rover1 waypoint3 waypoint2) (visible waypoint3 waypoint2) (can_traverse rover1 waypoint5 waypoint2) (visible waypoint5 waypoint2) (at_soil_sample waypoint5) (equipped_for_soil_analysis rover0) (store_of rover0store rover0) (empty rover0store) (at_rock_sample waypoint3) (equipped_for_rock_analysis rover1) (store_of rover1store rover1) (empty rover1store) (at_rock_sample waypoint5) (visible_from objective0 waypoint2) (visible_from objective0 waypoint5) (supports camera0 high_res) (supports camera1 high_res) (supports camera1 low_res) (can_traverse rover0 waypoint0 waypoint2) (can_traverse rover0 waypoint0 waypoint3) (visible waypoint0 waypoint3) (can_traverse rover0 waypoint0 waypoint4) (visible waypoint0 waypoint4) (can_traverse rover1 waypoint1 waypoint3) (visible waypoint1 waypoint3) (visible_from objective0 waypoint0) (at_lander general waypoint4) (channel_free general) (visible waypoint1 waypoint4) (visible waypoint3 waypoint4) (can_traverse rover0 waypoint3 waypoint0) (visible waypoint3 waypoint0) (can_traverse rover0 waypoint4 waypoint0) (visible waypoint4 waypoint0) (visible_from objective0 waypoint3) (visible_from objective0 waypoint4) (visible waypoint0 waypoint5) (visible waypoint5 waypoint0) (visible waypoint4 waypoint3) (visible waypoint4 waypoint1) (visible waypoint5 waypoint3) (visible waypoint3 waypoint5) (_TRUE) }.
> Plan is valid:false

But there were also errors for the childsnack domain, though this looks to me like another problem - like an action from the rover domain was used:

> Testing planner on /home/jeremias/Programmieren/KIT/APS/aquaplanning/benchmarks/Childsnack/p01.pddl
> [126,501] Error at step 6: Action (navigate rover0 waypoint4 waypoint1) PRE: {  {0, 1, 2, 3} } POST: {  {4} ; NOT {1} }} is not applicable in state { (at_kitchen_bread bread1) (at_kitchen_content content1) (notexist sandw1) (notexist sandw2) (at tray1 kitchen) (at tray2 kitchen) (at tray3 kitchen) (at tray3 table1) (not_allergic_gluten child1) (waiting child1 table1) (_TRUE) }.
> Plan is valid:false

Can you confirm these errors?

**Comment by domschrei** [comment] 2019-01-28 12:31
Thanks a lot. 

The first error with the derived predicates has already been fixed in the feature branch, but this did not find its way into the master branch yet. I added the fix now.

The invalid plans in the ParallelPlanner tests were caused by the fact that the plan is not reset to `null` if a single planner object is used for multiple instances in a row. I fixed it. 

The last error with the wrong domain should also be caused by that bug. Can you test if everything works now?

**Comment by jtrautmann** [comment] 2019-01-28 13:17
I can confirm that the errors are fixed, thank you.
Unfortunately, there now is a new error (or I just didn't notice it before) in the `testSatPlanner` method in `TestParallelPlanning`:

> Testing planner on /home/jeremias/Programmieren/KIT/APS/aquaplanning/benchmarks/Barman/domain.pddl, /home/jeremias/Programmieren/KIT/APS/aquaplanning/benchmarks/Barman/p01.pddl
> 0 : (grasp left shaker1)
> 1 : (grasp left shot1)
> 2 : (grasp left shot2)
> 3 : (fill-shot shot1 ingredient1 left right dispenser1)
> 4 : (fill-shot shot1 ingredient3 left right dispenser3)
> 5 : (fill-shot shot2 ingredient5 left right dispenser5)
> 6 : (pour-shot-to-clean-shaker shot1 ingredient1 shaker1 left l0 l1)
> 7 : (pour-shot-to-clean-shaker shot1 ingredient3 shaker1 left l0 l1)
> 8 : (empty-shot left shot2 ingredient5)
> 9 : (clean-shot shot1 ingredient1 left right)
> 10 : (shake cocktail1 ingredient3 ingredient1 shaker1 left right)
> 11 : (clean-shot shot2 ingredient5 left right)
> 12 : (empty-shaker left shaker1 cocktail1 l1 l0)
> 13 : (pour-shaker-to-shot cocktail1 shot1 left shaker1 l1 l0)
> 
> [57,460] Error at step 2: Action (grasp left shot1) PRE: {  {1, 3} } POST: {  {4} ; NOT {1, 3} }} is not applicable in state { (holding left shaker1) (ontable shot1) (ontable shot2) (handempty right) (dispenses dispenser1 ingredient1) (empty shot1) (clean shot1) (dispenses dispenser2 ingredient2) (dispenses dispenser3 ingredient3) (dispenses dispenser4 ingredient4) (dispenses dispenser5 ingredient5) (empty shot2) (clean shot2) (empty shaker1) (clean shaker1) (shaker-level shaker1 l0) (next l0 l1) (next l1 l2) (cocktail-part1 cocktail1 ingredient3) (cocktail-part2 cocktail1 ingredient1) (shaker-empty-level shaker1 l0) (_TRUE) }.
> Plan is valid:false

**Comment by domschrei** [comment] 2019-01-28 16:05
I'll clarify this with Tomas later, but I'm pretty sure that this is (against all common sense) intended behaviour. The flag `ignoreAtMostOneAction` is set, so the SAT planner will omit some constraints and the resulting encoding naturally leads to invalid plans. Setting `spp.setIgnoreAtMostOneAction(true);` should output valid plans again.

**Closed** 2019-01-31 08:39 UTC
